=== MathieuPaillart/Engineering-School-XSLT/bdd_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:attribute name="label" type="xs:string"/>
    <xs:element name="lecture" type="lectureType"/>
    <xs:complexType name="lectureType">
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:element name="lectures">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="lecture"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="lectureKey">
            <xs:selector xpath="lecture"/>
            <xs:field xpath="@name"/>
        </xs:key>
    </xs:element>
    <xs:complexType name="person">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="DoB" type="xs:string"/>
            <xs:element name="phoneNumber" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:choice>
                <xs:element name="situation" type="xs:string"/>
                <xs:element name="adress" type="xs:string"/>
                <xs:element name="zipcode" type="xs:string"/>
                <xs:element name="city" type="xs:string"/>
                <xs:element name="country" type="xs:string"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="studentType">
        <xs:complexContent>
            <xs:extension base="person">
                <xs:sequence>
                    <xs:element name="idStudent" type="xs:string"/>
                    <xs:element name="moyenne" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="promotionType">
        <xs:sequence>
            <xs:element name="promotionStudents">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="studentref" type="xs:string" maxOccurs="100"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="lectures">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="lectureRef" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="studentList">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="studentref" type="xs:string" maxOccurs="100"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="teacherList">
                                        <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="teacherref" type="xs:string" maxOccurs="100"/>
                                        </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="ref-lecture" type="xs:string"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute ref="label"/>
    </xs:complexType>

    <xs:complexType name="departmentType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="promotion" type="promotionType"/>
        </xs:sequence>
        <xs:attribute ref="label"/>
    </xs:complexType>

    <xs:element name='engineeringSchool'>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="students">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="student" type="studentType" maxOccurs="unbounded">
                                <xs:unique name="uniqueStudentNumber">
                                    <xs:selector xpath="student"/>
                                    <xs:field xpath="idStudent"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="teachers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="teacher" minOccurs="1"
                                        maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="person">
                                            <xs:sequence>
                                                <xs:element name="idTeacher" type="xs:string"/>
                                            </xs:sequence>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                                <xs:unique name="uniqueTeacherNumber">
                                    <xs:selector xpath="teacher"/>
                                    <xs:field xpath="idTeacher"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>

                    </xs:complexType>
                </xs:element>
                <xs:element ref="lectures">
                </xs:element>
                <xs:element maxOccurs="unbounded" name="department" type="departmentType"/>
            </xs:sequence>
            <xs:attribute ref="label"/>
            <xs:attribute name="city" type="xs:string"/>
        </xs:complexType>
        <xs:key name="teacherKey">
            <xs:selector xpath="./teachers/teacher"/>
            <xs:field xpath="idTeacher"/>
        </xs:key>
        <xs:keyref name="teacherKeyRef" refer="teacherKey">
            <xs:selector xpath="lectures/lecture/teacherList/teacherRef"/>
            <xs:field xpath="."/>
        </xs:keyref>
        <xs:keyref name="lecturesKeyRef" refer="lectureKey">
            <xs:selector xpath="department/promotion/lectures/lectureRef"/>
            <xs:field xpath="@ref-lecture"/>
        </xs:keyref>
        <xs:key name="StudentKey">
            <xs:selector xpath="./students/student"/>
            <xs:field xpath="idStudent"/>
        </xs:key>
        <xs:keyref name="CourseStudentRef" refer="StudentKey">
            <xs:selector xpath="./lectures/lecture/studentList/studentRef"/>
            <xs:field xpath="."/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== MathieuPaillart/Engineering-School-XSLT/bdd.xml
<?xml version = "1.0" encoding="UTF-8"?>
<?xml-stylesheet href="index.css" type="text/css"?>
<?xml-stylesheet type="text/xsl" href="scenar2.xsl" ?>
<!DOCTYPE engineeringSchool>
<engineeringSchool label="Polytech" city="Nice" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="bdd_schema.xsd">
    Voici l'école d'ingénieur Polytech Nice Sophia et ses merveilleux élèves :
    <students>
        <student>
            <name>Paillart</name>
            <firstName>Mathieu</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>mathieu.paillart@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>11119999</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Paillart</name>
            <firstName>Mathieu</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>mathieu.paillart@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>22222222</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Lopez</name>
            <firstName>Laura</firstName>
            <DoB>07/11/1996</DoB>
            <phoneNumber>0672520748</phoneNumber>
            <email>laura.lopez1@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>33333333</idStudent>
			<moyenne>18</moyenne>
        </student>
        <student>
            <name>Croene</name>
            <firstName>Hugo</firstName>
            <DoB>07/11/1996</DoB>
            <phoneNumber>0672520748</phoneNumber>
            <email>hugo.croene@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>12345678</idStudent>
			<moyenne>9</moyenne>
        </student>
        <student>
            <name>Humbert</name>
            <firstName>Alix</firstName>
            <DoB>07/11/1996</DoB>
            <phoneNumber>0672520748</phoneNumber>
            <email>alix.humbert@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>55555555</idStudent>
			<moyenne>10</moyenne>
        </student>
        <student>
            <name>Ferré</name>
            <firstName>Jérémi</firstName>
            <DoB>07/11/1996</DoB>
            <phoneNumber>0672520748</phoneNumber>
            <email>jeremi.ferre@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>21401234</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Pillone</name>
            <firstName>Prune</firstName>
            <DoB>24/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>prune.pillone@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>21080812</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Gardin</name>
            <firstName>Alexis</firstName>
            <DoB>14/05/1995</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>alexis.gardin@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>21078808</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Defranoux</name>
            <firstName>Alexis</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>alexis.defranoux@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>2108038</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Bouis</name>
            <firstName>Maxime</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>maxime.bouis@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>21080808</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Durant</name>
            <firstName>Clément</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>clement.durant@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>57322222</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Masson</name>
            <firstName>Alexanne</firstName>
            <DoB>07/11/1996</DoB>
            <phoneNumber>0672520748</phoneNumber>
            <email>alexanne.masson@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>89989999</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Simon</name>
            <firstName>Serrano</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>simon.serrano@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>11111111</idStudent>
			<moyenne>8</moyenne>
        </student>
        <student>
            <name>Leroux</name>
            <firstName>Camille</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>camille.leroux@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>99999999</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Julien</name>
            <firstName>Camille</firstName>
            <DoB>07/11/1996</DoB>
            <phoneNumber>0672520748</phoneNumber>
            <email>camille.julien@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>88888888</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Ssegura</name>
            <firstName>Alexis</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>alexis.segura@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>77777777</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Tosello</name>
            <firstName>Sebastien</firstName>
            <DoB>07/11/1996</DoB>
            <phoneNumber>0672520748</phoneNumber>
            <email>sebastien.tosello@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>66666666</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Dupont</name>
            <firstName>Paul</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>paul.dupont@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>98765432</idStudent>
			<moyenne>14</moyenne>
        </student>
        <student>
            <name>Jurozek</name>
            <firstName>Florian</firstName>
            <DoB>14/07/1997</DoB>
            <phoneNumber>0608080808</phoneNumber>
            <email>florian.jurozek@etu.unice.fr</email>
            <country>FRANCE</country>
            <idStudent>444444444</idStudent>
			<moyenne>14</moyenne>
        </student>
    </students>
	Sa magnifique équipe enseignante : 
    <teachers>
        <teacher>
            <name>Papazian</name>
            <firstName>Christophe</firstName>
            <DoB>14/08/75</DoB>
            <phoneNumber>0320320323</phoneNumber>
            <email>Chistophe.Papazian@unice.fr</email>
            <country>France</country>
            <idTeacher>1</idTeacher>
        </teacher>
        <teacher>
            <name>Mosser</name>
            <firstName>Sebastien</firstName>
            <DoB>17/10/86</DoB>
            <phoneNumber>0320320323</phoneNumber>
            <email>Sebastien.Mosser@unice.fr</email>
            <country>Canada</country>
            <idTeacher>2</idTeacher>
        </teacher>
        <teacher>
            <name>Faron</name>
            <firstName>Catherine</firstName>
            <DoB>17/10/70</DoB>
            <phoneNumber>0320320323</phoneNumber>
            <email>Catherine.Faron@unice.fr</email>
            <country>France</country>
            <idTeacher>3</idTeacher>
        </teacher>
        <teacher>
            <name>Deantoni</name>
            <firstName>Julien</firstName>
            <DoB>09/10/87</DoB>
            <phoneNumber>0320320323</phoneNumber>
            <email>Julien.Deantoni@etu.unice.fr</email>
            <country>France</country>
            <idTeacher>4</idTeacher>
        </teacher>
        <teacher>
            <name>Collet</name>
            <firstName>Philippe</firstName>
            <DoB>17/10/95</DoB>
            <phoneNumber>0320320323</phoneNumber>
            <email>Philippe.Collet@unice.fr</email>
            <country>France</country>
            <idTeacher>5</idTeacher>
        </teacher>
    </teachers>
    Ainsi que des cours géniaux qui sont les suivants :
    <lectures>
        <lecture name="anglais">
        </lecture>
        <lecture name="info">
            <maintenue>true</maintenue>
        </lecture>
        <lecture name="maths">
            <maintenue>false</maintenue>
        </lecture>
        <lecture name="japonais">
            <maintenue>false</maintenue>
        </lecture>
        <lecture name="philosophie"/>
    </lectures>
    <department label="SI">
        <promotion label="SI3">
			<promotionStudents>
				<studentref>55555555</studentref>
				<studentref>99999999</studentref>
				<studentref>11111111</studentref>
			</promotionStudents>
            <lectures>
                <lectureRef ref-lecture="anglais">
                    <studentList>
                        <studentref>55555555</studentref>
                    </studentList>
                    <teacherList>
                        <teacherref>1</teacherref>
                    </teacherList>
                </lectureRef>
